---
- name: Enable Linked Connections in registry
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: EnableLinkedConnections
    data: 1
    type: dword

- name: Add credential and map drive
  win_shell: |
    cmdkey /add:{{ drive.server }}\{{ drive.share_name }} /user:{{ domain_name}}\{{ drive.username }} /pass:{{ drive.password }}
  args:
    executable: cmd
  register: drive_map_results
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: '{{ ansible_user }}'
    ansible_become_pass: '{{ ansible_password }}'

- name: Map drive
  win_shell: |
    net use {{ drive.drive_letter }}: \\{{ drive.server }}\{{ drive.share_name }} /persistent:yes
  args:
    executable: cmd
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: '{{ ansible_user }}'
    ansible_become_pass: '{{ ansible_password }}'
...