---
- name: Install AD CS
  win_feature:
    name: AD-Certificate
    state: present
    include_sub_features: true
    include_management_tools: true
  register: win_feature

- name: Install-WindowsFeature ADCS-Cert-Authority
  ansible.windows.win_feature:
    name: ADCS-Cert-Authority
    state: present
    include_management_tools: true
...