---
- name: Ensure service accounts are created
  microsoft.ad.user:
    identity: "{{ service_account.identity }}"
    password: "{{ service_account.password }}"
    description: "{{ service_account.description }}"
    state: "{{ service_account.state }}"
    path: "{{ service_account.path }},DC={{ domain_name }},DC={{ domain_tld }}"
    groups:
      set: "{{ service_account.groups }}"
    spn:
      set: "{{ service_account.spn }}"
  loop: "{{ service_accounts }}"
  loop_control:
    loop_var: service_account
  no_log: true
...