---
- name: Disable SMB Signing if enabled
  ansible.windows.win_powershell:
    script: |
      try {
        Set-SmbClientConfiguration -RequireSecuritySignature $false -Force
        Set-SmbServerConfiguration -RequireSecuritySignature $false -Force
        $Ansible = @{ Changed = $true }
        $Ansible | ConvertTo-Json -Compress
      }
      catch {
        $Ansible = @{ Changed = $false; Failed = $true }
        $Ansible | ConvertTo-Json -Compress
      }
    error_action: stop
...
