---
- name: Disable SMB Signing if enabled
  ansible.windows.win_powershell:
    script: |
      try {
        $clientConfig = Get-SmbClientConfiguration
        $serverConfig = Get-SmbServerConfiguration

        if ($clientConfig.RequireSecuritySignature -or $serverConfig.RequireSecuritySignature) {
          Set-SmbClientConfiguration -RequireSecuritySignature $false -Force
          Set-SmbServerConfiguration -RequireSecuritySignature $false -Force
          $Ansible = @{ Changed = $true }
        }
        else {
          $Ansible = @{ Changed = $false }
        }
        $Ansible | ConvertTo-Json -Compress
      }
      catch {
        $Ansible = @{ Changed = $false; Failed = $true }
        $Ansible | ConvertTo-Json -Compress
      }
    error_action: stop
...
